### ISSUE TITLE
Wrong timestamp in Logstash pipeline causes ES to create Index

### ISSUE THREAD

**Issue by VictorCovalski** [logstash-plugins/logstash-filter-date#105]
I'm using Elastic Stack for centralized log management purposes. Filebeat is my shipper, and it's tailing system log files like Syslog. Usually things work like a charm, although every now and then syslog-ng outputs logs with erroneous timestamps, or repeats old ones. Since my environment is large and highly distributed, It is hard to fix these issues by inspecting each one of them when they ocurr. 

I just got this one today(August 7).

**Jun  1 17:17:01** omitted CRON[31352]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

When this event is parsed, I get the date Jun 1 which the Date filter parses correctly and overwrites the @timestamp in the event with June 1st 2017, 17:17:01.000 . This causes Elasticsearch to create an index for this event alone, which is troublesome for maintaining index backups* in my environment.

I'd like to propose an option in the date filter which would ignore the date obtained by parsing the event if the date doesn't match a restriction (like being 1 day old), and instead would keep the @timestamp generated from when the log was collected. This would prevent Elasticsearch from creating additional indices when erroneous logs are generated.

**Comment by jordansissel** [comment]
> ignore the date obtained by parsing the event if the date doesn't match a restriction (like being 1 day old), and instead would keep the @timestamp generated from when the log was collected

You can achieve this with filters, though I personally wouldn't do this because replacing one incorrect timestamp with another incorrect timestamp seems like not solving the thing. The filters folks often use for this are a combination of mutate, date, and ruby filters.

* Use 'mutate' filter to copy the original `@timestamp` to a separate field
* Use 'date' filter as you are doing today
* Use 'ruby' filter to do the age check and use the original timestamp copied by the mutate filter in place of the one specified in the log.
