### ISSUE TITLE
date filter is quite expensive 

### ISSUE THREAD

**Issue by dshelepov** [logstash-plugins/logstash-filter-date#5]
I did some microbenchmarking (VM, 4 cores, 4 GB of ram, Ubuntu), and it appears the date filter can be quite hard-hitting in terms of affecting throughput.  

I used the following config: http://pastebin.com/itvj3QDX (change filenames to get working paths/ permissions).

I tested with this artificial data: http://pastebin.com/ywJXk0yR multiplied by 20000 (`seq 1 20000 | xargs -Inone cat data.template > data.in`).  The resulting input file was approximately 100MB in size.

`java version "1.7.0_72"`
`Java(TM) SE Runtime Environment (build 1.7.0_72-b14)`
`Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)`

`LOGSTASH_VERSION = "1.4.1"`

---

I tested three runs: one with the exact config I referred to, one with `date` clause remove and one that had all filters removed (i.e.: pure I/O).  My results were:
- trivial config: 0:45 CPU / 0:22 wallclock to completion
- no date clause config: 1:58 / 1:08
- full config: 3:00 / 1:57

This roughly matches what I have seen on my production config and data.   It is evident that including the date filter accounts for 30-40% of the cost of running the config.  Perhaps there is a way to shave some time off date filter performance?

Note that my event stream includes both date formats used in the config (with and without ms), and I have already optimized it to check the more common format first.

I have not checked the code of the date filter too closely (it appears to hand off all the expensive work to a Java library, inside which I haven't looked at all), but two algorithmic ideas come to mind that could at least theoretically offer speedups.  
- Consecutive events often share a large portion of the timestamp (perhaps only differing in s or ms fields).  Come up with an algorithm that would quickly detect whether a newly arrived time string only differs from the one previously seen by those fields and if so, simply modify the previously seen timestamp directly instead of reparsing the string from scratch.  This is quite challenging to implement, especially for the general case.
- Cache most recent string-to-date mappings observed.  Unfortunately this is almost useless when timestamps come in at ms precision, as most events may have unique timestamps.

**Comment by dshelepov** [comment]
I opened this based on a suggestion from jordansissel offered in https://github.com/logstash-plugins/logstash-filter-date/issues/3 .

**Comment by jordansissel** [comment]
First, thank you *so much* for putting in the energy for the analysis here.

I agree date filter performance needs to be better.

On your config, I think we need to improve your pattern to more closely match real-world scenarios. The date format "MMM d ..." matches `Jan 7` (one space), not `Jan  7` (two spaces). To fix this, we'll actually need two different patterns (one with 2 spaces and 1 `d` and one with 1 space and  `dd`):

`"MMM  d HH:mm:ss", "MMM dd HH:mm:ss", "MMM  d HH:mm:ss.SSS", "MMM dd HH:mm:ss.SSS"`

In testing your pattern against `Jan  7 04:54:07.465"` I get `:exception=>java.lang.IllegalArgumentException: Invalid format: "Jan  7 04:54:07.465" is malformed at " 7 04:54:07.465"` due to the two-space problem I described.

## What we know from the past

Filling in what I remember from past experiments - I have observed that failed date parsing is quite expensive. In your config, you have two date patterns: `"MMM d HH:mm:ss", "MMM d HH:mm:ss.SSS"`. Your sample log has this format of time: `Jan  7 04:54:07.465`. 

Because of the ordering, and your test data, logstash will always try the first pattern (no millisecond precision), fail, and try the second pattern and succeed.

## Perf testing

With the "fixed" date patterns (spacing!) I mentioned above, and this command line:

```
bin/logstash -e 'input { generator { message => "Jan  7 04:54:07.465" } } filter { date { match => [ "message", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss", "MMM  d HH:mm:ss.SSS", "MMM dd HH:mm:ss.SSS" ] } } output { stdout { codec => dots } }'  | pv -War > /dev/null
```

* WIth this above config: 2,220 events/sec
* With no date, but an empty `mutate { }` filter:  83,800 events/sec
* With a reordered `match` with `MMM  d HH:mm:ss.SSS` first: 26,200 events/sec

Note: the `|pv -War > /dev/null` is a trick I use to measure event throughput. The `dots` codec emits one dot `.` per event and pv measures bandwidth (bytes) - easy way to get event rate  :)

---

The data above shows that,  for this sample log set, with a reordered date pattern having the "correct" pattern occur first, we get a 10x throughput boost.

What is the cause? I'm not entirely sure (and it's nearly naptime for me, so I"Ll investigate another day). I will say the date filter code is quite old and may not be the best implementation.

If there are no other solutions, we could maintain some kind of LRU or frequency-ordered list of the `match` setting that would reorder patterns to be the most efficient during runtime.

**Comment by dshelepov** [comment]
Thanks for your fast response, Jordan, I appreciate it as well.  A couple of points.  

Firstly, I'm aware of the two-space problem.  I had multiple patterns previously, and it turned out that this wasn't the most ideal approach, so I instead introduced the mutate clause to normalize all timestamps to 1 space.  On my real data, this showed real improvement, so unless I messed something up, I expect this is still the case for the setup I provided.  This is the normalization clause (just before the date filter):

    mutate {
        gsub => [ "ttime", "  ", " " ]
    }

As far as the ordering.  I found out early on that ordering plays a major part, and spent some time arriving at the optimal config (which is the same as what I have pasted minus a bunch of other, much rarer patterns that don't show up on the perf radar at all).  After that I could no longer get any major improvements by reordering.  This is contrary to what you report, so perhaps my production data is split between ms and no-ms formats approximately 50/50 and therefore I cannot see the major savings you're describing.  Anyway, I'll try reordering the patterns on the test example I provided and report back the results.

**Comment by dshelepov** [comment]
I tried reordering the patterns, and I found this was even slower, which is not surprising, because >50% of my sample data does not have ms in timestamps.  

However I tried introducing a clause that would append `.000` upon finding a timestamp that does not have a `.` character, and removed the shorter pattern entirely.  This indeed helped bring down the cost of the filter significantly.  Unfortunately it is more difficult to deploy in prod, because I have to deal with a larger set of possible timestamps here.  But at least I know where to direct my efforts now.

 - trivial config: 0:45 CPU / 0:22 wallclock to completion
 - no date clause config: 1:58 / 1:08
 - full config: 3:00 / 1:57
 - *full config with reordered patterns: 3:20 / 2:13*
 - *coerce ms onto all timestamps: 2:08 / 1:18*

Anyway, since at the end of this exercise the cost of the date filter is under 10% of my test scenario under ideal conditions, feel free to resolve the issue without fixing anything.  On the other hand, any improvements that would help with perf in the face of multiple formats (like dynamic pattern reordering that you've suggested) could be helpful.  But it is probably lo-pri compared to other logstash improvements.

**Comment by jordansissel** [comment]
I did some experiments here with respect to date filter performance during a failed match.

Some sample code to test the cost of a certain number of parse failures when multiple matches are given:

```ruby
require "logstash/filters/date"
require "logstash/event"
require "benchmark"

iterations = 10_000
puts "Loop count: #{iterations}"
Benchmark.bmbm do |r|
  10.times do |i|
    patterns = [ *i.times.map { "YYYY" }, "ISO8601" ]
    date = LogStash::Filters::Date.new("match" => [ "foo", *patterns ])
    date.register

    r.report("YYYY(#{i}), ISO8601") do
      iterations.times do 
        event = LogStash::Event.new("foo" => "2001-01-01T08:00:00.000Z")
        date.filter(event)
      end
    end
  end
end
```

The performances gets significantly worse as the number of failed parses per-event increases.


```
YYYY(0), ISO8601   0.270000   0.000000   0.270000 (  0.270000)
YYYY(1), ISO8601   3.060000   0.020000   3.080000 (  2.944000)
YYYY(2), ISO8601   5.830000   0.060000   5.890000 (  6.164000)
YYYY(3), ISO8601   8.300000   0.060000   8.360000 (  8.663000)
YYYY(4), ISO8601  11.380000   0.090000  11.470000 ( 11.204000)
...
```

With 0 failures, speed is fairly fast (0.27 seconds for 10,000 events; ~37,000 per second). At 1 failure, we slow down _significantly_ (90%!!!) and it gets worse at 2 failures, then 3, etc.

Sampling cpu with visualvm shows this:

<img width="891" alt="screen shot 2015-12-01 at 7 45 22 pm" src="https://cloud.githubusercontent.com/assets/131818/11521838/531affd0-9865-11e5-808b-632a476a26c3.png">

Joda will raise an exception if the time parse fails, and JRuby will wrap this exception before handing it to our code. It appears most of the time is spent generating the stack trace - something we don't even _use_ in most cases. Funky.

This phenomenon is mentioned on [JRuby's performance tips page](https://github.com/jruby/jruby/wiki/PerformanceTuning#common-profiling-hotspots) and on a recent [JRuby blog entry about rescue/exception performance](http://blog.jruby.org/2015/10/performance_improvements_in_jruby_9030/).

Some thoughts for next steps (which I will do if I can tonight)

- See if we can avoid using exceptions for failure detection
- See if JRuby 9.0.3.0 fixes this

**Comment by jordansissel** [comment]
Moved my prior comment into a new ticket - #41

**Comment by jordansissel** [comment]
#74 solves this.
